### ISSUE TITLE
Error 

### ISSUE THREAD

**Issue by batrlatom** [virajmavani/semi-auto-image-annotation-tool#13]
Hello,
after installing according instructions, I am getting such error:

ValueError: Cannot use 'filtered_detections/map/while/strided_slice_2' as input to 'filtered_detections/map/while/ones/packed' because 'filtered_detections/map/while/strided_slice_2' is in a while loop. See info log for more details.

I have a python 3.6, tensorflow 1.14, keras 2.3.1

Normal retinanet from fizyr works fine for me. Do you know where could be the problem?

**Comment by deeplearning666** [comment]
Hello! I have the same  environment with you. Have you solve it?
Thanks!

**Comment by Varat7v2** [comment]
I am also getting the same error? What would be the solution of the above mentioned problem?
