### ISSUE TITLE
strided_slice_2 value error

### ISSUE THREAD

**Issue by Varat7v2** [virajmavani/semi-auto-image-annotation-tool#16]
Hi Virajmavani, I am having the following problem when I am trying to run your main.py script. What would be the reason of this issue? My keras version is 2.3.1 and tensorflow version is 1.14.0.

`ValueError: Cannot use 'filtered_detections/map/while/strided_slice_2' as input to 'filtered_detections/map/while/ones/packed' because 'filtered_detections/map/while/strided_slice_2' is in a while loop. See info log for more details.`

**Comment by virajmavani** [comment]
Hi @Varat7v2!

Here is a link to another issue posted on one of the dependencies' Git repository.
https://github.com/fizyr/keras-retinanet/issues/1118

It seems that using keras==2.2.5 and keras-retinanet==0.5.1 should do the trick here.

**Comment by Varat7v2** [comment]
@virajmavani I pulled the recent git and finally it got worked. Thank you very much.

**Comment by Varat7v2** [comment]
How long will take to detect using keras pre-trained model that you have shared? When I did as per your instructions, its always showing `processing || Image number 1/0` message on console. Is there any mistakes I might have done?
