### ISSUE TITLE
Icon data missing

### ISSUE THREAD

**Issue by jinfagang** [virajmavani/semi-auto-image-annotation-tool#4]
When running `python3 main.py`, there is something wrong:
```
/usr/local/lib/python3.6/site-packages/keras/models.py:282: UserWarning: No training configuration found in save file: the model was *not* compiled. Compile it manually.
  warnings.warn('No training configuration found in save file: '
Traceback (most recent call last):
  File "main.py", line 439, in <module>
    imgicon = PhotoImage(file='icon.png')
  File "/usr/local/Cellar/python/3.6.5/Frameworks/Python.framework/Versions/3.6/lib/python3.6/tkinter/__init__.py", line 3542, in __init__
    Image.__init__(self, 'photo', name, cnf, master, **kw)
  File "/usr/local/Cellar/python/3.6.5/Frameworks/Python.framework/Versions/3.6/lib/python3.6/tkinter/__init__.py", line 3498, in __init__
    self.tk.call(('image', 'create', imgtype, name,) + options)
_tkinter.TclError: couldn't recognize data in image file "icon.png"
```

icon missing?

**Comment by virajmavani** [comment]
It seems to work fine here. On what OS are you trying this?

**Comment by jinfagang** [comment]
@virajmavani on macOS Sir.

**Comment by virajmavani** [comment]
What version of Tkinter are you running? To check, do the following in your Python prompt,

>> import tkinter
>> tkinter.TkVersion
8.5

Version 8.6 of Tkinter is not platform independent and so the issue with loading PNG files. Try using tkinter version 8.5 and it shall work. If it doesn't, do tell us again and we will work on it.

**Comment by virajmavani** [comment]
Okay. So it seems that the suggestion that I gave won't work. Tried it myself. I have solved it and will push to the master in a while. Thanks for pointing this out.

**Comment by virajmavani** [comment]
I have push to the master. It shall work fine now. I am closing this issue.
