### ISSUE TITLE
Image Directory doesn't load after cancelling the AskDirectory Dialog

### ISSUE THREAD

**Issue by AyeshaGurnani** [virajmavani/semi-auto-image-annotation-tool#6]
After cancelling a wrongly pressed Open Directory button, the current directory in which I am working fails to respond to the Next and Previous buttons and throws the following error:

`
Exception in Tkinter callback
Traceback (most recent call last):
  File "C:\Users\Viraj\Anaconda3\lib\tkinter\__init__.py", line 1699, in __call__
    return self.func(*args)
  File "main.py", line 172, in open_image_dir
    self.imageList = os.listdir(self.imageDir)
FileNotFoundError: [WinError 3] The system cannot find the path specified: ' '
`

**Comment by virajmavani** [comment]
Thank you Ayesha for pointing that out. I see that there exists a similar problem with opening single images.

**Comment by virajmavani** [comment]
Solved the bug. Thanks for reporting.
