### ISSUE TITLE
Support for converting csv annotation files to PASVAL VOC datasets

### ISSUE THREAD

**Issue by songgongjun** [virajmavani/semi-auto-image-annotation-tool#7]
Hello, I have generated a csv file after using your python code, but I want to convert it into an xml file of the PASVAL VOC dataset. Is there any way you can do this, preferably the python code?

**Comment by virajmavani** [comment]
Hello! I have added the functionality in the 'dev' branch but I still need to test it using different cases. Kindly help me out by testing it for your use case and post here if you find any bug.
Thanks!

**Comment by china56321** [comment]
> Hello, I have generated a csv file after using your python code, but I want to convert it into an xml file of the PASVAL VOC dataset. Is there any way you can do this, preferably the python code?

@songgongjun  have you solved this problem?  convert csv to xml ?could you post the code ? thank you !

**Comment by virajmavani** [comment]
@china56321 It is in the 'dev' branch. Kindly check the branch for the code. It should be working fine.

**Comment by virajmavani** [comment]
@china56321 The issue has been resolved in PR #15
